spring.application.name=ChatService
server.port=8085

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://kanchuganesh789:Master%40123@nursery.7amnd.mongodb.net/ces_content?retryWrites=true&w=majority&appName=nursery}
spring.mongodb.uri=${MONGODB_URI:mongodb+srv://kanchuganesh789:Master%40123@nursery.7amnd.mongodb.net/ces_content?retryWrites=true&w=majority&appName=nursery}

# Eureka
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/

# Actuator
management.endpoints.web.exposure.include=*
